### ISSUE TITLE
Mapping object with null properties is not working

### ISSUE THREAD

**Issue by m-i-c-h-a-l** [ugoevola/ts-mapstruct#11]
Mapping an object containing a property with null value is not working. The error:

TypeError: Cannot convert undefined or null to object
   at Function.entries (<anonymous>)
   at Object.clean (/opt/microservices/node_modules/ts-mapstruct/dist/src/utils/utils.js:89:12)
   at /opt/microservices/node_modules/ts-mapstruct/dist/src/utils/utils.js:94:21
   at Array.forEach (<anonymous>)
   at Object.clean (/opt/microservices/node_modules/ts-mapstruct/dist/src/utils/utils.js:89:28)
...

**Comment by ugoevola** [comment]
thank you for your analysis, I correct that
